### ISSUE TITLE
Missing file screen_capture_lite_shared.dll 

### ISSUE THREAD

**Issue by clobotorre** [smasherprog/screen_capture_lite#113]
Example_CSharp project has a reference to a file called screen_capture_lite_shared.dll, wich I can't find in the repo. So, when I try to compile this project I get an error complaining about this file.

How can I get this missing file?

**Comment by smasherprog** [comment]
Use cmake to build everything and you will get those dll's

**Comment by smasherprog** [comment]
they must be built as they are c++ dlls not csharp

**Comment by smasherprog** [comment]
Gonna close this unless theres something new to add
