### ISSUE TITLE
Mac OS example code gave incorrect color order

### ISSUE THREAD

**Issue by EMCP** [smasherprog/screen_capture_lite#117]
I've been working with the coding example (really helps and well done!). the one issue was, on Mac OS the colors were flipped.. 

I fixed it by negating the logic at this line from
https://github.com/smasherprog/screen_capture_lite/blob/master/Example_CPP/Screen_Capture_Example.cpp#L27

```
 if (img.isContiguous) {
        memcpy(imgdist, imgsrc, dst_size);
    } else { 
        for (auto h = 0; h < Height(img); h++) {
            auto startimgsrc = imgsrc;
            for (auto w = 0; w < Width(img); w++) {
                *imgdist++ = imgsrc->R;
                *imgdist++ = imgsrc->G;
                *imgdist++ = imgsrc->B;
                *imgdist++ = 0; // alpha should be zero
                imgsrc++;
            }
            imgsrc = SL::Screen_Capture::GotoNextRow(img, startimgsrc);
        }
    }
```

to 

```
 if (!img.isContiguous) {
        memcpy(imgdist, imgsrc, dst_size);
    } else { 
        for (auto h = 0; h < Height(img); h++) {
            auto startimgsrc = imgsrc;
            for (auto w = 0; w < Width(img); w++) {
                *imgdist++ = imgsrc->R;
                *imgdist++ = imgsrc->G;
                *imgdist++ = imgsrc->B;
                *imgdist++ = 0; // alpha should be zero
                imgsrc++;
            }
            imgsrc = SL::Screen_Capture::GotoNextRow(img, startimgsrc);
        }
    }
```

I am unsure why it is but... the colors are now perfect.. just wanted to share

**Comment by smasherprog** [comment]
Are you sure its not in some code to display the image? For example, Did you try the example and save the file to disk using the tje_encode_to_file ?
Is the color not correct in this case as well?

**Comment by EMCP** [comment]
I am quite noob to C++, so much so I didn't really dare modify the example otherwise.. especially in the encoder function..

**Comment by smasherprog** [comment]
Can you try using the example code and uncommenting the save to file code path. Then open the images up and see if the colors are correct or incorrect?
this line here https://github.com/smasherprog/screen_capture_lite/blob/3badb36ec9a7246033898a7de453321e67fb3c3f/Example_CPP/Screen_Capture_Example.cpp#L184

**Comment by EMCP** [comment]
here's what I uncommented


https://github.com/smasherprog/screen_capture_lite/blob/3badb36ec9a7246033898a7de453321e67fb3c3f/Example_CPP/Screen_Capture_Example.cpp#L178-L186

Attached are the Dock, VS Code.. both of which show reversed Blues and Reds I believe

<img width="374" alt="Screen Shot 2021-11-21 at 12 00 04" src="https://user-images.githubuserc
<img width="225" alt="Screen Shot 2021-11-21 at 11 59 54" src="https://user-images.githubusercontent.com/3691722/142759139-56e051dd-2c08-42b5-b386-e4bc6e9fe155.png">
ontent.com/3691722/142759134-6b5dffe7-b1b8-4c46-a324-de4d8dd3d129.png">

**Comment by smasherprog** [comment]
Hmm yeah ill revisit and check that out.   In the mean time, the format is here https://github.com/smasherprog/screen_capture_lite/blob/3badb36ec9a7246033898a7de453321e67fb3c3f/src_cpp/ios/NSFrameProcessor.mm#L20

**Comment by smasherprog** [comment]
If anyone reads this and uses a mac, can you comment if you are experiencing this or post if colors work as expected.

**Comment by EMCP** [comment]
If it matters this is seen on a 2018 Mac Mini (Intel), with latest Monterey OS

**Comment by smasherprog** [comment]
So, thanks for posting on this. I finally dusted off my mac mini and was able to see that this is happening. I also am adding some permission checking code, and will fix this on mac!

**Comment by smasherprog** [comment]
It appears this was a bug across all platforms, so i updated the example. Thanks for finding this

**Comment by smasherprog** [comment]
Check out the new code. Should be fixed now in master

**Comment by EMCP** [comment]
Glad to help where I can, thanks 👍
