### ISSUE TITLE
About onFrameChanged data source

### ISSUE THREAD

**Issue by logic-coder** [smasherprog/screen_capture_lite#123]
Hi, why not use official function：GetFrameDirtyRects [https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgioutputduplication-getframedirtyrects](url) to get changed rectangles?

Isn't this function more efficient？

What's wrong with this function?

**Comment by smasherprog** [comment]
It might be. If you want to do a Pull request with the codechange ill accept it!
The current method in code is very fast and works for all platforms so i went that direction.
But again.. Always happy to get some pull requests :)

**Comment by logic-coder** [comment]
OK, If I'm successful, I will push the Pull request.

**Comment by smasherprog** [comment]
going to close this
