### ISSUE TITLE
Deadlocks in the code

### ISSUE THREAD

**Issue by TopoIogist** [smasherprog/screen_capture_lite#127]
I am encountering deadlocks in my program which I could trace back to screen capture lite..

Changing the "Screen_Capture_Example.cpp" example slightly to this:
```
int main() {
    for(int i = 0; i < 100; ++i) {
        std::cout << "Iteration " << i << std::endl;
        createwindowgrabber();
        std::this_thread::sleep_for(std::chrono::seconds(2));
    }
}
```
and in createwindowgrabber 

```
std::string srchterm = "Calculator";
...
framgrabber->setFrameChangeInterval(std::chrono::milliseconds(500));
    framgrabber->setMouseChangeInterval(std::chrono::milliseconds(500));
```

To trigger the issue I am opening up and closing many calc.exe windows. At some point a race condition occurs and the iteration counter does not progress anymore...

```
Iteration 6
ADDING WINDOW  Height 771  Width  1026   Calculator
ADDING WINDOW  Height 771  Width  1026   Calculator
ADDING WINDOW  Height 771  Width  1026   Calculator
ADDING WINDOW  Height 771  Width  1026   Calculator
ADDING WINDOW  Height 771  Width  1026   Calculator
ADDING WINDOW  Height 771  Width  1026   Calculator
ADDING WINDOW  Height 771  Width  1026   Calculator
ADDING WINDOW  Height 771  Width  1026   Calculator
onNewFrame fps0
Exiting Thread due to expected error
Iteration 7
```

**Comment by TopoIogist** [comment]
Basically what happens is this I think:
The shared pointer gets destroyed and sets the TerminateThreadEvent bool. Then simultaneously this "cleanup code" in ScreenCapture.cpp
related to the exception just removes the TerminateThreadsEvent bool...
```
                        Thread_Data_->CommonData_.TerminateThreadsEvent = false;
                        // Clean up
                        std::this_thread::sleep_for(std::chrono::milliseconds(1000)); // sleep for 1 second since an error occcured
                        ```

**Comment by smasherprog** [comment]
Yeah I see that.. good catch!

There does appear to be a race between the start and the destructor running. I just pushed a change to master. Let me know if that works

**Comment by TopoIogist** [comment]
Yes looks fixed with the update
