### ISSUE TITLE
bug,crash

### ISSUE THREAD

**Issue by introspection3** [smasherprog/screen_capture_lite#128]
![image](https://user-images.githubusercontent.com/12368358/148528668-5eecba0c-0077-4f8c-919d-f08761ddc674.png)

**Comment by introspection3** [comment]
It is not recommended to add an assertion in the middle of the function, it is usually an exception
![image](https://user-images.githubusercontent.com/12368358/148529150-38c07eb6-4707-49fb-aee0-777a0bdaf3f4.png)

**Comment by smasherprog** [comment]
Were you able to figure out the bug? Pull requests are welcome. From the screenshot, there isnt enough information.

**Comment by introspection3** [comment]
@smasherprog are you oline? you can download a aspia client,i will give you a account ,you can remove control my  pc

**Comment by introspection3** [comment]
@smasherprog I have two monitor

**Comment by smasherprog** [comment]
I did re review your snapshot. In the demo code you are running the window capturing is testing. If you dont have a window matching the name in the code, the application will crash. Try changing the test to find a window that you have open to capture.

**Comment by introspection3** [comment]
@smasherprog may be :I adjust two monitors's  default order

**Comment by introspection3** [comment]
![image](https://user-images.githubusercontent.com/12368358/148675593-0f4a6356-1810-4348-87fb-c78c3edb2360.png)

**Comment by smasherprog** [comment]
Try taking a screenshot without the assert pop up in the way. I want to see the monitor dimensions listed in the window.

**Comment by introspection3** [comment]
![image](https://user-images.githubusercontent.com/12368358/149075830-f9771040-a91f-4614-93d7-17bf3a68bec5.png)

**Comment by introspection3** [comment]
@smasherprog

**Comment by smasherprog** [comment]
I havent had time to look into this just yet but I will.

**Comment by smasherprog** [comment]
I am interested to see what the monitor values are contained in it. Could you get those values? 
base.Imagebuffereize
monheight
srcrowstride
dstrowstride

These values in the image 
![image](https://user-images.githubusercontent.com/3393733/149425872-5e5df8b0-fff9-4e59-882f-d0ece3868ed7.png)

**Comment by introspection3** [comment]
dear sir ,you are too lazy as I'm here waiting for you three days.....
I have searched solution but not found it,you can give me a exe with log

**Comment by smasherprog** [comment]
I did just push an update to change the assert. It might fix it, since I cannot reproduce your problem

**Comment by introspection3** [comment]
@smasherprog good job! sir how to resolve it?

**Comment by introspection3** [comment]
with this lib,I think you should have a new remote desktop software

**Comment by smasherprog** [comment]
glad to hear its fixed!
