### ISSUE TITLE
Running as SYSTEM user can't capture screen

### ISSUE THREAD

**Issue by wang332127858** [smasherprog/screen_capture_lite#133]
I was not yet able to capture the login screen using this method. Microsoft's documentation for IDXGIAdapter::EnumOutputs states "If you call this API in a Session 0 process, it returns DXGI_ERROR_NOT_CURRENTLY_AVAILABLE." On the login screen there are no other sessions yet so it seems impossible to get the capture running.

**Comment by wang332127858** [comment]
https://blog.actorsfit.com/a?ID=00350-adeb5c91-f0d7-488e-bc98-0530d8e3e916
But can't fetch after switching user

**Comment by smasherprog** [comment]
Correct capturing the screen on windows is Way way beyond this library. It involves changing users, starting the application as administrator.. etc. Its not trivial for sure!

**Comment by smasherprog** [comment]
Gonna close this. Please create a new issue if something is found!
