### ISSUE TITLE
Building window 7 version

### ISSUE THREAD

**Issue by gaoming627** [smasherprog/screen_capture_lite#140]
It was written to support win 7 platform so I am building window 7 version but I got some issues.

So my questions are followings:

1. Is it possible to build for win 7 32bit/64bit version?
2. If it is possible, can you provide me some guides?
3. If it is impossible, what is the minimum version of window that we can build? 

Looking forward to your kindly reply.

Thank you.

**Comment by smasherprog** [comment]
1. yes
2. I use cmake so you just need to download that to generate your solution.
3. this originally supported windows xp and probably still does! I just dont want to advertise that its supported.

**Comment by gaoming627** [comment]
Thank you for your reply.

I also used cmake to generate codeblock project with mingw32.
https://prnt.sc/AuYFk0_rZSeu
As you see, it gives some issues but I got finally cb project file.
When building cb project file, I got this.
https://prnt.sc/h_6643_eHIoo
After changed PW_RENDERFULLCONTENT with PW_CLIENTONLY, I got following.
https://prnt.sc/FOdBXmCm6zbj

My environment are following:
windows 7 ultimate service pack1 32bit
cmake 3.24.2
codeblocks 20.03
winlibs-i686-posix-dwarf-gcc-10.3.0-llvm-12.0.0-mingw-w64-9.0.0-r2

Please let me know what I was wrong to build successfully.

**Comment by gaoming627** [comment]
Excuse me but can you let me know what tools can I use to build your source for win 7 32bit build?

**Comment by smasherprog** [comment]
going to close this
