### ISSUE TITLE
Capturing Multiple monitors together.

### ISSUE THREAD

**Issue by xtremekratos** [smasherprog/screen_capture_lite#142]
Is it possible to Capture Multiple monitors together at a time? 
If so how exactly can it be done
also is there any plans to implement it.
Thank you..

**Comment by smasherprog** [comment]
monitors are captured separately. Its up to the developer to glue them together. This is mostly because the Operating system methods to capture is based on capturing a monitor or a window, not groups.

**Comment by xtremekratos** [comment]
Thank You.
