### ISSUE TITLE
How do I use the newest release as a library in a C# project?

### ISSUE THREAD

**Issue by philhk** [smasherprog/screen_capture_lite#147]
This is probably a pretty noob question but I just can't find out how I can use library in my project. I tried to add the dll's in the bin folder as a reference to my project but the only dll that worked was the one with csharp at the end but I'm not sure if that is right because the file is only 3KB and I wasn't able to use the namespace SCL. I would be very happy if someone could help me.

**Comment by smasherprog** [comment]
Theres an example in the repo. Build everything and use that to get started.

**Comment by smasherprog** [comment]
going to close unless theres a bug. The examples should work. Post an issue if building everything fails.
