### ISSUE TITLE
Is cursor on Windows guaranteed to be always 32x32 in size?

### ISSUE THREAD

**Issue by SAOMDVN** [smasherprog/screen_capture_lite#153]
I am developing for Windows only and I noticed that whenever mouse image is changed, it stays a consistent 32x32 size image. I wonder if this is always the case (at least on Windows) so that I doesn't have to reallocate memory lest size changes?

**Comment by smasherprog** [comment]
i think soo.... ?   Youd have to google its been a while since i looked into that.
