### ISSUE TITLE
GetMonitors in a virtual machine

### ISSUE THREAD

**Issue by Berets** [smasherprog/screen_capture_lite#161]
Hi, if i try to get frames from a virtual machine i can't the monitor, it works only if i connect before on RDP

There's not a way to make it work without?

**Comment by smasherprog** [comment]
The reason it would work is because there is NO desktop before you log in. If you want it to work, you have to stay logged into the VM.

**Comment by smasherprog** [comment]
There is nothing to capture until you log in, then when you log out, the desktop session ends. Not sure how to keep your session active
