### ISSUE TITLE
Mac Partial Capture needs implementation

### ISSUE THREAD

**Issue by smasherprog** [smasherprog/screen_capture_lite#25]
I have to do more bounds checking on the captured monitors...
Mac isnt implemented yet. Might be a performance looser for the mac platform.. need to do research on this.
Windows and linux are implemented. Windows could use a little more cleanup.

**Comment by smasherprog** [comment]
Need help with the mac version on this. Currently the entire screen is captured and there is no perf gain. Need more research on this and implementation

**Comment by grz0zrg** [comment]
Did you tried CGDisplayCreateImageForRect ? (Note: i have about zero knowledge about Mac platform)

https://developer.apple.com/documentation/coregraphics/1454595-cgdisplaycreateimageforrect

**Comment by smasherprog** [comment]
that looks exactly what i need --thanks
Yeah same here, most of my work is on windows.
I am out this weekend and only have my laptop with me so I wont be able to implement this until Monday.
Ill add this then.. thanks for the help

**Comment by smasherprog** [comment]
working on this now.. it will be done in a few hours

**Comment by smasherprog** [comment]
Code updated on master.
it gave a performance increase as well if capturing smaller amounts of data.

**Comment by smasherprog** [comment]
Closing issue new code released 
https://github.com/smasherprog/screen_capture_lite/releases/tag/v10.2.0
