### ISSUE TITLE
capture lock and login screen Windows

### ISSUE THREAD

**Issue by boonkerz** [smasherprog/screen_capture_lite#26]
Is it possible to capture login screen within an windows service?

**Comment by smasherprog** [comment]
Yes, the code will capture the screens properly if the code is added to run as a service. I built this specifically for that purpose.

**Comment by smasherprog** [comment]
The hard part is writing the service to change to the active session.. A brief article on some of that https://blogs.technet.microsoft.com/askperf/2007/07/24/sessions-desktops-and-windows-stations/

**Comment by boonkerz** [comment]
yea but this is not implemented yet?

**Comment by smasherprog** [comment]
A windows service to capture the screen is beyond the scope of this library. But you want to know how its done, you can check this code out
https://github.com/smasherprog/RemoteDesktop/tree/master/RemoteDesktopServer_Library

**Comment by smasherprog** [comment]
I am closing this as beyond the scope of this library. Please ask any questions though as I have done what you are looking for and I can point you in the right directions.

**Comment by Berets** [comment]
Hi i'm trying C# dll in a WPF project, but when i lock the screen while the application running, it stop to register frames, even if i run as admin.

**Comment by smasherprog** [comment]
This is way beyond the scope of this program. I posted above where I have done this.
You need to run the program as a service in order to capture LOCK screens or the UAC pop up stuff.
This is NON trivial and needs to be written into the application, not the library
