### ISSUE TITLE
Support for signle window capture ?

### ISSUE THREAD

**Issue by namkazt** [smasherprog/screen_capture_lite#29]
my next point in my app is single window capture. Any ideas how to achieve that ?

**Comment by smasherprog** [comment]
ill look into this.. On windows, I think its possible. But ill check this out over the weekened

**Comment by smasherprog** [comment]
as a fallback,, it would be possible to get the dimensions of the window and only capture that so it is possible

**Comment by smasherprog** [comment]
I am implementing Windows, Linux then mac.

Almost done with Windows now...

**Comment by namkazt** [comment]
great, thanks.






*
              Best Regards.Mr. Nam NguyễnPhone No. : 012.9595.8685*

*Skype Account : nam.kazt*



2017-08-06 5:35 GMT+07:00 Scott <notifications@github.com>:

**Comment by smasherprog** [comment]
Windows should be done in master right now
Working on the Linux code now.

**Comment by smasherprog** [comment]
Linux should be done and in master now too

**Comment by namkazt** [comment]
@smasherprog looking good man. I'm not test it yet but definitely today.
Also i see you return a list of Windows on config functions. Is it capture a list of windows ?

**Comment by smasherprog** [comment]
yeah it will capture a list of windows.

**Comment by smasherprog** [comment]
theres likely still bugs, but I am trying to figure out each platforms details first.

**Comment by namkazt** [comment]
cool, i'm testing on old version there is some crash ( framegrabber ) but was use in release version so it just display critical error. Will put here if it happen one more time.

**Comment by namkazt** [comment]
also is image result from NewFrame or FrameChange thread safe ?

**Comment by smasherprog** [comment]
If you get a crash include as much information as possible.

I am working on the mac implementation now

**Comment by smasherprog** [comment]
The entire library is thread-safe.

**Comment by smasherprog** [comment]
Mac is almost done
It works when the desktop isnt scaled.
I have to add checks for scaling and retina displays.

**Comment by smasherprog** [comment]
I havent completed the work on macs. It will work if there isnt any scaling, but I have to think about how I want to handle it in a way that makes sense and also is fast.  Until then, windows and linux implementations should work fine.

**Comment by smasherprog** [comment]
If you want to jump in and do some Pull Requests they are welcome :)

**Comment by namkazt** [comment]
@smasherprog  is there any way to directly set screen size in with this lib?
I think capture lower resolution ( 640x480 for example ) is faster and also faster in encoding for my side.

**Comment by smasherprog** [comment]
https://github.com/smasherprog/screen_capture_lite/blob/master/Example/Screen_Capture_Example.cpp#L36

See my commented out code. It shows how to get just a 512x512 square. It doesnt have to be a power of two, but its best to stick with numbers that are powers of two because it will be a little faster.

What are you capturing that isnt fast enough? I have tested this on

low end mac mini  -- I think i was able to hit 60 fps at 1080
linux virtualized -- over 200 fps
windows over 60 fps as well.

I am away from my workstation right now, but the library should be pretty darn fast for most needs. 
If you post a link to your code I can take a look at it too..

**Comment by namkazt** [comment]
yeah but it still have to do in many thing in 1 frame like:
1, capture frame ( your lib ) example size: 1920x1024
2, resize to 400x240 
3, get difference from old frame
4, send ...

so if i want to capture fullscreen but in 640x480 resolution (step 1 ) it will much more faster to do next steps.

but any way im just asking.

**Comment by smasherprog** [comment]
so, sure you can capture part of the monitor using the above code link.

**Comment by smasherprog** [comment]
Also, if you post your code, I can take a look and offer advise

**Comment by namkazt** [comment]
yeah. thanks. i will update after finish current version






*
              Best Regards.Mr. Nam NguyễnPhone No. : 012.9595.8685*

*Skype Account : nam.kazt*



2017-08-24 3:55 GMT+07:00 Scott <notifications@github.com>:

**Comment by smasherprog** [comment]
Window capturing done for all platforms: win, linux and mac
