### ISSUE TITLE
"Unexpected error" when starting certain applications during screen capture, causing capture to abort

### ISSUE THREAD

**Issue by inantop** [smasherprog/screen_capture_lite#31]
Hi again! :) I'm using your excellent library to build an always-on screen frame grabber for a personal project. I have a Qt application window outputting the captured frames, and I was displaying it on my second monitor while I tried to do some common tasks on my main display which was being captured.

I found that launching certain applications (example: "The Guild 2: Renaissance," which is an older game) resulted in the capture stopping until I started it up again. To be clear, the capture stopped _as_ the application started up, but I could alt+tab away and re-start the capture once the game had loaded. I traced the problem to a `DXGI_ERROR_INVALID_CALL` from `_DuplLock->ReleaseFrame()` https://github.com/smasherprog/screen_capture_lite/blob/5a82135571a9bea0498d48f9a70c6663bd9498fb/src/windows/DXFrameProcessor.cpp#L282 which eventually causes the thread to stop as it's not in the list of expected errors. 

For my own purposes, adding `DXGI_ERROR_INVALID_CALL` to `FrameInfoExpectedErrors[]` https://github.com/smasherprog/screen_capture_lite/blob/5a82135571a9bea0498d48f9a70c6663bd9498fb/src/windows/DXFrameProcessor.cpp#L57-L62 allowed capture to continue during the start-up and into the game. I'm not sure if this is an appropriate solution, but FYI in either case.

**Comment by smasherprog** [comment]
So, adding that DXGI_ERROR_INVALID_CALL  as an expected error will make it work?
If so ill add that when I get home shortly.
Is there any more info on the error that you can provide? I think that there might be a way to ask for more information about an error, similiar to GetLastError()
If not, ill just add this fix and continue on with life .. ..

**Comment by smasherprog** [comment]
Added expected error to the array

**Comment by smasherprog** [comment]
Merged into master

**Comment by inantop** [comment]
ah sorry for not getting back to you sooner! I haven't been able to get back to working on this for a little while, I will try to remember to do this next time and let you know. I appreciate your promptness!

**Comment by smasherprog** [comment]
Sure just let know if you have any problems or suggestions!
