### ISSUE TITLE
windows 10 duplication api error 

### ISSUE THREAD

**Issue by peererror** [smasherprog/screen_capture_lite#38]
HI ,
I am getting following error when I try to capture screen  on some systems . 
Failed to get duplicate output in DUPLICATIONMANAGER	Error
DirectX Desktop Duplication not supprted, falling back to GDI Capturing . . .

**Comment by smasherprog** [comment]
I just started getting this too.. Ill check into it now

**Comment by smasherprog** [comment]
I believe I found the issue and I added a check to the code that will assert this is true.
For me I was creating multiple instances of the capture library without destroy the previous one.

For example

framgrabber = createframegrabber();

In the above code, if the createframegrabber function creates an instance AND there is a previous instance held in the framegrabber object, then two will exist at the same time. This was causing DX to freak out.  So, first do something like this

framgrabber = nullptr;
framgrabber = createframegrabber();

This will ensure the object is destroyed first then created after.  I updated the library to assert when multiple instances exist at once.   Let me know if this fixes the problem

**Comment by smasherprog** [comment]
Master has been updated so you can try it out.

**Comment by peererror** [comment]
ok.let you know the results  .

**Comment by smasherprog** [comment]
Closing this as I believe it should be fixed in above. Ill reopen if you tell me its not fixed.
