### ISSUE TITLE
Last updates broke Linux

### ISSUE THREAD

**Issue by hardillb** [smasherprog/screen_capture_lite#39]
The last set of updates seam to have broken Linux.

When I call `ExtractAndConvertToRGB` or `ExtractAndConvertToRGB565` I'm getting a sigsegv.

For a 128x128 image it looks like it's managing to process the first 2 lines (so the address returned for img.Data is at 256 bytes before somewhere it can't access) but falls over trying to access the first pixel of the 3rd line.

**Comment by hardillb** [comment]
The example app is also falling over in `X11FrameProcessor::ProcessFrame` when trying to do a partial capture.

(I'm running on ubuntu 16.04)

**Comment by hardillb** [comment]
reverting back to before the x11 and linux update works again

**Comment by smasherprog** [comment]
I was coding while watching a movie and not paying much attention. Linux looks like it was working the whole time.

Reverted in master
