### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by randydom** [smasherprog/screen_capture_lite#40]
Hello , please does the screen-capture lite support the Android Dev ? .

so many thanks ,
Yours,Randy

**Comment by smasherprog** [comment]
No.
Capturing of android requires a different approach.

**Comment by randydom** [comment]
Hello , is there any future or roadmap to support Android ?

**Comment by smasherprog** [comment]
no support for android or Iphone.
Its not possible because of how capturing works on these operating systems

**Comment by randydom** [comment]
Hi Scott , please do you know any android / iPhone capture library ? Or a
cross-platform one ( that support these ) ?

**Comment by smasherprog** [comment]
There are none.
Use MediaProjectionManager  for capturting on android
IOS you cannot capture the screen. The only thing you can do is have the user take screen shots one at a time.

**Comment by randydom** [comment]
Scott , really wondering how does TeamViewer do that on both Android and
IOS , or is this a different approach ?

**Comment by smasherprog** [comment]
team viewer doesnt do it on ios
on android they use MediaProjectionManager

**Comment by smasherprog** [comment]
my company uses teamviewer and the only thing the ios version does it is allow a user to take a screen shot and chat.

**Comment by smasherprog** [comment]
but you cannot stream the screen automatically like you can on android

**Comment by randydom** [comment]
Ah ok , so many thanks Scott for this great help .

**Comment by smasherprog** [comment]
NM.. you have to do this on IOS
https://community.teamviewer.com/t5/Knowledge-Base/How-can-I-share-the-screen-on-my-iPad-iPhone-with-TeamViewer/ta-p/4734

**Comment by smasherprog** [comment]
It was just added with the last OS 11, but its still a clunky way.

**Comment by smasherprog** [comment]
If you want to write it and do a pull request. please do.
