### ISSUE TITLE
no callback to call on frame tick.

### ISSUE THREAD

**Issue by namkazt** [smasherprog/screen_capture_lite#41]
I was checked that OnNewFrame callback only calls when mouse change or desktop change. if everything does not change then it will not be called. that make my record data unable to continue if screen image not moving. 
is there any change i can get a callback like OnFrameTick(Image img, .. ) if img not change then still use last frame.

**Comment by smasherprog** [comment]
You're saying that onnewframe doesnt not get called if the mouse doesnt move and the desktop image doesnt change?

What Operating system are you using ?

**Comment by smasherprog** [comment]
On windows, onnewframe will always be called even if the mouse doesnt move and the desktop image doesnt change. I would double check your code because I would bet that you paused the library and did not resume it

**Comment by smasherprog** [comment]
Closing this because I dont believe this is an error in the library.

If you get more information ill reopen this issue.
