### ISSUE TITLE
is it not a bug?

### ISSUE THREAD

**Issue by shine1145** [smasherprog/screen_capture_lite#42]
https://github.com/smasherprog/screen_capture_lite/blob/6071cd6d0eba1b1c2fca6882767509794bc81a5b/include/ThreadManager.h#L46

the mouse thread seems to take frame-timer instead of mouse-timer.
sharing frame-timer from mouse thread with frame-capture thread can lead to irregular capture frequency.

**Comment by smasherprog** [comment]
Just fixed this. It is a bug as you pointed out

**Comment by smasherprog** [comment]
Just created a new release on this as well.
