### ISSUE TITLE
Screen capturing stopped after sometime  and calling ~ScreenCaptureManager() hangs on Thread_.join();

### ISSUE THREAD

**Issue by peererror** [smasherprog/screen_capture_lite#44]
Hi , 
I am trying to recode the screen into video file . The library capturescreen like 20 to 50 mins after that it stop calling onNewframe and on this state If I call ~ScreenCaptureManager() it hanged on 

```
else if (Thread_.joinable()) {
                Thread_.join(); //hangs here 
            }
            ScreenCaptureManagerExists = false;
```

**Comment by smasherprog** [comment]
Are you using the latest release of this library? 14.0.8

**Comment by smasherprog** [comment]
It sounds like you might have a dead lock in your code. Try letting the program run without calling your video encode and see if it still hangs. My guess is that the hanging on its destructor is because you have some code that is deadlocked somewhere so the thread cannot join

**Comment by peererror** [comment]
OK code where this happen is  ~ScreenCaptureManager()  function of the library . Is deadlock in my code will affect the destructor of the code library code  ?

**Comment by smasherprog** [comment]
I need more information than this. I believe the bug is in your code.

**Comment by peererror** [comment]
OK let me get back with more info

**Comment by peererror** [comment]
yes it was problem in my code

**Comment by smasherprog** [comment]
Glad to hear you figured it out.
