### ISSUE TITLE
 SL::Screen_Capture::GetMonitors() returns empty vector

### ISSUE THREAD

**Issue by FennecFix** [smasherprog/screen_capture_lite#45]
windows 10, msvc

**Comment by smasherprog** [comment]
Can you step through the GetMonitoprs.cpp file, like 18  and see what the StateFlags are for each of your monitors?

**Comment by FennecFix** [comment]
Yes, that worked. Thank you!

**Comment by smasherprog** [comment]
Thanks for finding this. A new release has been published
