### ISSUE TITLE
New logo / icon

### ISSUE THREAD

**Issue by mansya** [smasherprog/screen_capture_lite#54]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by smasherprog** [comment]
Sure ill accept a cool logo for this app and make sure to reference you as the author.

**Comment by smasherprog** [comment]
i mean library

**Comment by mansya** [comment]
I have design logo for this apps. do you like it ? what do you think ?
![screen capture lite](https://user-images.githubusercontent.com/33461607/41506950-03ff353c-7252-11e8-84c3-6babcec03b28.png)

**Comment by mansya** [comment]
I have design logo for this app. do you like it ? what do you think ?
![screen capture lite](https://user-images.githubusercontent.com/33461607/41506997-f94753ee-7252-11e8-99f9-d790524183d2.png)

**Comment by smasherprog** [comment]
Nice! looks good to me. Ill post this later today on the landing page here with Credit to you.
Thanks..

**Comment by smasherprog** [comment]
Readme updated with the logo. Let me know if you had a different idea.

**Comment by mansya** [comment]
I have uploaded all the files to this link.
https://drive.google.com/open?id=16jikPduXt3a31edcd3Zl8Ki8u6FumQlf

and I have sent you pull requests. please check. it looks more interesting in your github
