### ISSUE TITLE
Segmentation fault 11

### ISSUE THREAD

**Issue by AlanMaxwell** [smasherprog/screen_capture_lite#55]
I'm trying to launch the example in Mac OS terminal, so I get this error:

$ ./Example/screen_capture_example 
Starting Capture Demo/Test
Testing captured monitor bounds check
Id=69732992 Index=0 Height=1600 Width=2560 OffsetX=0 OffsetY=0 Name=Monitor 69732992
Id=69732992 Index=0 Height=1601 Width=2560 OffsetX=0 OffsetY=0 Name=Monitor 69732992
Id=69732992 Index=0 Height=1600 Width=2561 OffsetX=0 OffsetY=0 Name=Monitor 69732992
Running display capturing for 10 seconds
Library is requesting the list of monitors to capture!
Id=69732992 Index=0 Height=1600 Width=2560 OffsetX=0 OffsetY=0 Name=Monitor 69732992
onNewFrame fps9
onNewFrame fps10
onNewFrame fps11
onNewFrame fps10
onNewFrame fps11
onNewFrame fps10
onNewFrame fps11
onNewFrame fps11
onNewFrame fps10
Running window capturing for 10 seconds
Running Partial display capturing for 10 seconds
Library is requesting the list of monitors to capture!
Id=69732992 Index=0 Height=512 Width=512 OffsetX=512 OffsetY=512 Name=Monitor 69732992
onNewFrame fps0
Segmentation fault: 11

**Comment by smasherprog** [comment]
I am away from my mac for the weekend, ill take a look at this in a few days. Feel free to check it out yourself too... I like PR!

**Comment by smasherprog** [comment]
Just ran this on my mac without error. So, I need more information. If you could debug the program it would help so I would know why you are getting the error.

**Comment by smasherprog** [comment]
Closing due to lack of information
