### ISSUE TITLE
when text zoom is set in the display settings, the mouse cursor  is incomplete.

### ISSUE THREAD

**Issue by mmOTAN** [smasherprog/screen_capture_lite#58]
Running on a high resolution WINDOWS 10 laptop, when text zoom is set in the display settings, the mouse cursor is captured, the mouse cursor image is incomplete.

**Comment by Joeasaurus** [comment]
I have a similar issue, I'm trying to call lines like this from the example, but in onMouseChanged:

```
ExtractAndConvertToRGBA(img, imgbuffer.get(), size);
tje_encode_to_file(s.c_str(), Width(img), Height(img), 4, (const unsigned char*)imgbuffer.get());
```

All I get is little black squares. Windows 10 VisStud 17

**Comment by smasherprog** [comment]
Where is this text zoom property? This is my setup and it works fine
![image](https://user-images.githubusercontent.com/3393733/51012488-36882f00-1512-11e9-8bba-0e72bc9b7ede.png)

**Comment by smasherprog** [comment]
On mouse changed returns an png basically
so you have to use the alpha returned
if (img) {
                    std::cout << "New mouse coordinates  AND NEW Image received."
                              << " x= " << mousepoint.Position.x << " y= " << mousepoint.Position.y << std::endl;
                    lodepng::encode(s, (unsigned char*)StartSrc(*img), Width(*img), Height(*img));

**Comment by Joeasaurus** [comment]
That works perfectly thank you!!

**Comment by smasherprog** [comment]
Also those image libraries are for demo only. I have only used them to prove that images are correct not for any other reason.. perf, etc

**Comment by Joeasaurus** [comment]
Yeah don't worry boss I was just getting my feet on the C++ again. Got it working slick now, thanks for all your work!! <3
