### ISSUE TITLE
 xHotspot and yHotspot 

### ISSUE THREAD

**Issue by mmOTAN** [smasherprog/screen_capture_lite#59]
In onMouseChanged, the location of the cursor is provided, but xHotspot and yHotspot are not provided. Can it be provided?

**Comment by smasherprog** [comment]
yeah it does look like this can be provided in a cross platform way. I am busy IRL at the moment so I wont be able to implement this soon. If you want to take a stab at it, please do

**Comment by smasherprog** [comment]
Just committed support for this.

**Comment by smasherprog** [comment]
working on all but ios.. ill fix this later today

**Comment by smasherprog** [comment]
New release with support for hotspot added

**Comment by meekaah** [comment]
hey sorry for the dumb question but i couldnt really figure out what was the mouse hotspot by just reading the code or by the values it outputs during debug, could you give me a hint? thanks
