### ISSUE TITLE
EnumWindows in GetWindows() crashes when encountering weird process name.

### ISSUE THREAD

**Issue by BhayanakMoth** [smasherprog/screen_capture_lite#60]
On Visual Studio 2017, When I tried the GetWindowFrame example, at the point where the EnumWindows() enumerates through processes it encounters a weird title name which crashes the program.
![devenv_2018-09-21_12-30-29](https://user-images.githubusercontent.com/17413156/45865284-a3788d00-bd9a-11e8-857e-0a17716800b8.png)

Here is the weird name string:
![devenv_2018-09-21_12-36-11](https://user-images.githubusercontent.com/17413156/45865392-f9e5cb80-bd9a-11e8-9ceb-e2b2c1ce377b.png)
I tested this part of the code seperately in CodeBlocks and it worked but it crashed in VS2017 but works on changing the type of name in Window struct from char[] to std::string. 

What should I do if I don't want to simply change the type? Another possible fix I can think of is check if the int value of char is < 0 and then change the string.

**Comment by smasherprog** [comment]
maybe you could test chancing the type to a wide string and see if that fixes it?

**Comment by smasherprog** [comment]
wait... I think it see a possible bug

Try adding \n to the end of the window name title after the copy is finished. It might be that it is not null terminated.

**Comment by BhayanakMoth** [comment]
Yep, added a null terminator and that fixed the problem. This problem is caused by buffer parameter in GetWindowTextA, which points to invalid window name string that is not null terminated.

**Comment by smasherprog** [comment]
awesome. did you want to do a pull request? Otherwise, ill fix this later today.

**Comment by smasherprog** [comment]
Just pushed a fix for this
try it out
