### ISSUE TITLE
Mac OS build fail

### ISSUE THREAD

**Issue by akasitskyi** [smasherprog/screen_capture_lite#61]
Hi, build fails on Mac OS Sierra.
cmake generation passees ok, but on the build phase I'm getting:

`bash-3.2$ cmake --build .
Scanning dependencies of target screen_capture_lite
[  6%] Building CXX object CMakeFiles/screen_capture_lite.dir/src/ScreenCapture.cpp.o
[ 13%] Building CXX object CMakeFiles/screen_capture_lite.dir/src/SCCommon.cpp.o
[ 20%] Building CXX object CMakeFiles/screen_capture_lite.dir/src/ThreadManager.cpp.o
[ 26%] Building CXX object CMakeFiles/screen_capture_lite.dir/src/ios/GetWindows.cpp.o
[ 33%] Building C object CMakeFiles/screen_capture_lite.dir/src/ios/NSMouseCapture.m.o
[ 40%] Building CXX object CMakeFiles/screen_capture_lite.dir/src/ios/NSFrameProcessor.cpp.o
[ 46%] Building CXX object CMakeFiles/screen_capture_lite.dir/src/ios/NSFrameProcessor.mm.o
/Users/admin/moba/screen_capture_lite/src/ios/NSFrameProcessor.mm:73:36: error: property 'enabled' not found on object of type 'id'
        self.output.connections[0].enabled = NO;
                                   ^
/Users/admin/moba/screen_capture_lite/src/ios/NSFrameProcessor.mm:80:36: error: property 'enabled' not found on object of type 'id'
        self.output.connections[0].enabled = YES;
                                   ^
2 errors generated.
make[2]: *** [CMakeFiles/screen_capture_lite.dir/src/ios/NSFrameProcessor.mm.o] Error 1
make[1]: *** [CMakeFiles/screen_capture_lite.dir/all] Error 2
make: *** [all] Error 2
`

`bash-3.2$ c++ --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.0.0`

Or am I doing something wrong?

**Comment by smasherprog** [comment]
very strange.....

Ill try this out later. This is the CI build for mac logs
https://travis-ci.org/smasherprog/screen_capture_lite/jobs/431973470
Maybe this might help

**Comment by smasherprog** [comment]
You can try building an xcode project,, that should work.
Also, can you check for updates? I think there is a newer version of xcode out which will update your build tools

**Comment by akasitskyi** [comment]
After updating xcode build works fine. Thank you!
