### ISSUE TITLE
Window title missing first char on Windows

### ISSUE THREAD

**Issue by YLiLarry** [smasherprog/screen_capture_lite#68]
What's the reason in `src/windows/GetWindows.cpp`, the function `EnumWindowsProc` puts a `\n` at the beginning of the window title retrieved? When I use it to get window titles, every first char is somehow missing. For example, window title "Task Manager" is incorrectly set as "\nask Manager". The issue apparently can be solved by simply removing the line `w.Name[textlen] = '\n';`.

**Comment by YLiLarry** [comment]
I don't understand the line
``````                                                                                       
             textlen = std::max(textlen - 1, static_cast<int>(sizeof(w.Name)) - 1);                                                   
             textlen = std::min(textlen, 0);  
``````
This second line is setting `textlen` to `0`. I believe this is a bug.

**Comment by smasherprog** [comment]
Thanks for pointing this out I just pushed a change It should fix this.
