### ISSUE TITLE
Bug with too long caption of window

### ISSUE THREAD

**Issue by zumm** [smasherprog/screen_capture_lite#69]
Hi. There is bug with code for windows.
Problem at this line https://github.com/smasherprog/screen_capture_lite/blob/master/src/windows/GetWindows.cpp#L24
If lenght of window caption is bigger than 128 then code does try write '\n' character to w.Name[128];

P.S.: Why do you even need to write \n to caption? GetWindowTextA returns only null terminated string.

**Comment by smasherprog** [comment]
Thanks for catching this 
Fixed in https://github.com/smasherprog/screen_capture_lite/commit/93de4bec9daaa95f7fcc7738ff031ef2dbc37bd9
