### ISSUE TITLE
why BGRA is used instead of just BGR?

### ISSUE THREAD

**Issue by YLiLarry** [smasherprog/screen_capture_lite#70]
May I ask a (stupid) question? Why does this library use 4 channels instead of just 3 for capturing screenshots? 

When is the alpha channel not entirely filled with 255? I'm asking because I'm trying to push the boundary of the capture frame rate, and I thought maybe using just 3 channels would be more efficient, also out of curiosity.

I saw that you mentioned the alpha channel is used in `onMouseChanged`, could you please elaborate what exactly the alpha channel represents in `onMouseChanged`?

Thanks.

**Comment by smasherprog** [comment]
working with a full 32 bits should be faster than 24 bits. I think that its not possible to get a 24 bit image naively in video cards. Directx doesnt even allow 24 bit image formats https://docs.microsoft.com/en-us/windows/desktop/api/dxgiformat/ne-dxgiformat-dxgi_format

So if you can show that using 24 bit images is faster than 32 bit, ill switch it.

**Comment by YLiLarry** [comment]
Ok thank you, that answered my question. I'll close this question.
