### ISSUE TITLE
Issue with DirectX12 on Windows

### ISSUE THREAD

**Issue by Electric-Turtle** [smasherprog/screen_capture_lite#72]
I have noticed that capturing applications running DirectX12 on Windows 10 produces nothing but black images (regardless of what is happening in the application). Any idea what would cause this behavior?

**Comment by smasherprog** [comment]
Ill take a look at it. I think its due to the difference in the framesize/pixel format.

**Comment by smasherprog** [comment]
I could not reproduce black images. I tried full screen star craft and was able to capture normally. Can you do a little debugging and see where the problem is? It shouldnt be that bad, this file is where all of the work is done https://github.com/smasherprog/screen_capture_lite/blob/master/src/windows/DXFrameProcessor.cpp

**Comment by smasherprog** [comment]
Theres an example file in this repo where you can capture and write the images to disk. Id start there as this is an easy way to test

**Comment by Electric-Turtle** [comment]
Yeah. I have been testing on F1 2019 http://www.formula1game.com/.

it has the option to run as either DirectX12 or DirectX11.

On DirectX11, everything works as expected.

On DirectX12, images are just black (except for the title bar, interestingly enough.).

**Comment by Electric-Turtle** [comment]
Looks like DXFrameProcessor explicitly uses the DirectX11 SDK. Could that be the underlying issue?

https://github.com/smasherprog/screen_capture_lite/blob/781732b6e605fe24eb9888dfd5b1bf15484c9edf/src/windows/DXFrameProcessor.cpp#L317

**Comment by smasherprog** [comment]
Yeah its very likely thats the case. I was going to look into this yesterday but got sidetracked. Ill for sure look at it now though.

**Comment by Electric-Turtle** [comment]
Awesome. I am not a skilled WIN32 programmer and I am certainly not a DirectX programmer, but it looks like Microsoft has a mechanism to ease the interchangeability of the two APIs.
https://docs.microsoft.com/en-us/windows/win32/direct3d12/direct3d-11-on-12

**Comment by smasherprog** [comment]
I cant reproduce what you are experiencing. I am running WOW using DX12. Attached is a screenshot taken using the example code here 
https://github.com/smasherprog/screen_capture_lite/blob/master/Example/Screen_Capture_Example.cpp
![82MONITORNEW_](https://user-images.githubusercontent.com/3393733/60761131-1041d880-9ff7-11e9-805c-16005efbefa0.jpg)

**Comment by smasherprog** [comment]
I was also able to capture windows as well without issue. Try using the example code to capture and save the images to disk to see if it works.

**Comment by smasherprog** [comment]
It could be that application is doing something it shouldnt be? Not sure. . . .

**Comment by Electric-Turtle** [comment]
Confirmed, exact same result when using the example code:
Results with DirectX11
![10WINNEW_DirectX11](https://user-images.githubusercontent.com/29153794/60773261-ea890200-a0d0-11e9-9321-0857cd62fdb5.jpg)

Exact same test procedure with DirectX12
![10WINNEW_DirectX12](https://user-images.githubusercontent.com/29153794/60773262-eceb5c00-a0d0-11e9-9c35-ed46b117a7ec.jpg)

Note the difference in the title bar (which is captured correctly in both cases)

**Comment by Electric-Turtle** [comment]
A manual PrtScr is able to capture the game just fine, even on DirectX12.

![printscreen_directx12](https://user-images.githubusercontent.com/29153794/60773324-bc57f200-a0d1-11e9-8260-1b286541ae37.png)

**Comment by smasherprog** [comment]
Strange.. I dont know whats going on.
Im going to try some other dx 12 examples/games and see if I can reproduce this.
Thanks for your efforts on this.

**Comment by Electric-Turtle** [comment]
No problem. You're the real MVP for making this library. It saved me a TON of effort on my project. I'll keep playing around with the game's settings to see if I can get it to work. In the meantime, the DirectX11 version works wells enough.

**Comment by Electric-Turtle** [comment]
stumbled across these when googling around for solutions:
https://github.com/microsoft/DirectXTK
https://github.com/Microsoft/DirectXTK12

It looks like Microsoft is finally acknowledging how terrible the interface for the DirectX APIs is and is making (slightly) convenient wrappers.

**Comment by smasherprog** [comment]
I've been trying dx 12 apps and even created a new dx12 project to try and create a bare-bones app to produce this and I cannot. 
Ill leave this issue open as I don't know why this specific application isn't capture-able  in dx 12 mode.

**Comment by Electric-Turtle** [comment]
I have a feeling the issue is one of the following:
1. A color space other than BGRA for the rendered images (perhaps HSV or something of the sort)
2. 16-bit images in DirectX12 mode.

Since the core implementation of screen_capture_lite assumes 8-bit BGRA images, supporting either of those things will require a fairly major overhaul. If DirectX12 compatibility becomes an absolute necessity, I may take it upon myself to propose a new architecture for such a change. But, for now anyways, I'll just keep the game running in DirectX11.

Thanks so much for looking into this!!!

**Comment by smasherprog** [comment]
https://github.com/smasherprog/screen_capture_lite/pull/89  should have fixed this now
