### ISSUE TITLE
Where to set window to capture

### ISSUE THREAD

**Issue by Outstep** [smasherprog/screen_capture_lite#73]
Hello,

I was researching cross platform  screen-capture libraries and came across your code.

I was able to compile the Example on my Ubuntu 18.04 and it ran through a number of capture exercises which seems to have been successful.

Now I will look over the code to try to get a feel for things but I was wondering how you can tell the library which application window to capture?   

Also, is there an easy way to have it capture applications sub-windows that might be created during a run?

I was thinking about how this might be used to augment seamless mode in remote screen captures for single applications.

Thanks

**Comment by smasherprog** [comment]
yes window example here.... 
 https://github.com/smasherprog/screen_capture_lite/blob/master/Example/Screen_Capture_Example.cpp#L282
you would need to recreate the IScreenCaptureManager if you want to add additional things to capture or change.
check out the example file above  i have examples on all of your questions

**Comment by smasherprog** [comment]
Closing as this issue is resolved
