### ISSUE TITLE
Failure on Windows 10

### ISSUE THREAD

**Issue by ababo** [smasherprog/screen_capture_lite#79]
I get the following output (and no frames retrieved):

> Exiting Thread due to expected error
> Exiting Thread due to Unexpected error

On OSX and Linux it works properly.

Note: On some Windows machines it works only for a first time after reboot, and then fails as described above.

**Comment by ababo** [comment]
I use `onNewFrame()` method to get frames. Subscribing to `onFrameChanged` causes segfault (do you have some documentation explaining difference between these two events?).

**Comment by ababo** [comment]
In some cases no error is shown, but the screen in black.

**Comment by smasherprog** [comment]
Do you get this when running the example program included in this repo?

**Comment by smasherprog** [comment]
Could you try running the examples in the repo here?

**Comment by ababo** [comment]
It looks that's my bug, sorry for the false alarm. Closing the issue.
