### ISSUE TITLE
Cursor image not working in linux

### ISSUE THREAD

**Issue by amunhoz** [smasherprog/screen_capture_lite#83]
I've used the same code of example:
` lodepng::encode(s, (unsigned char*)StartSrc(*img), Width(*img), Height(*img));`

And its producing an transparent png without any cursor image.
Any ideas?

gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by smasherprog** [comment]
i like issues that close themselves!  I hope that you found the solution to the problem. Let me know if you didnt
