### ISSUE TITLE
Filtering windows to the list a user might care about

### ISSUE THREAD

**Issue by JoeLudwig** [smasherprog/screen_capture_lite#86]
The list returned by `SL::Screen_Capture::GetWindows()` is quite long and full of unnamed windows, offscreen windows, etc.  They're all legit HWNDs, I'm sure, but only a small subset are appropriate to show in a list of windows a user might want to capture images from.

What's the best way to filter this list down to a more user-appropriate subset?

**Comment by smasherprog** [comment]
U can see the examples  
https://github.com/smasherprog/screen_capture_lite/blob/master/Example/Screen_Capture_Example.cpp#L191
You have to search through to find the one you are interested in. In the example, I only get windows with    cmake      in the name

**Comment by smasherprog** [comment]
In the callback you return the list of windows that you want to watch. This is called periodically, so it can change over time if you want.

**Comment by JoeLudwig** [comment]
I get that I can filter it. I guess my question is how I SHOULD filter it. Are the size_t Handle fields the actual HWND, which would let me ask Windows APIs about the window to get more information?

At least on Windows the name of the window itself isn't a very helpful filter. There's a lot of cruft in the list.

**Comment by smasherprog** [comment]
So what is it you are trying to get? You need to know ahead of time which windows you are wanting to get.. either a name or some other piece of info

**Comment by smasherprog** [comment]
I mean are you trying to get some random window that is better than 512? give me some info as to what you are looking for

**Comment by JoeLudwig** [comment]
I'm working on a tool that will let a user stream a window from their desktop into their VR headset. When they say they want to stream a thing, I want to show them a list of stuff to pick from. I'm planning to start streams on all viable candidates and show them the actual images of the windows (possibly scaled down or at a reduced frame rate for the picking part of this.) Then I'll start a stream of just that window.

At the time I'm writing the code, I have no idea what apps the user will be running or what the names of those windows will be. I need to leave that up to the user. I'm just trying to make that as easy on them as possible. By filtering out windows that are less than 40x40 pixels or that don't have names I can get that list down to about 50 windows. But the actual number of visible windows is more like 10.

**Comment by smasherprog** [comment]
Im open to extend the Window class and add some properties. If you want to do a Pull request with your ideas we can add it?

**Comment by baluoteliz** [comment]
if (!IsWindowVisible(hwnd))
            return true;

        if (!IsWindowEnabled(hwnd))
            return true;

        long lstyle = GetWindowLong(hwnd, GWL_STYLE);
        if ((lstyle & WS_CHILDWINDOW))
            return true;

        HWND parentWnd = (HWND)GetWindowLong(hwnd, GWL_HWNDPARENT);
        if (IsWindowEnabled(parentWnd))
            return true;

		if (IsWindowVisible(parentWnd))
            return true;

the code snippet is from WetRtc. maybe useful to you

**Comment by smasherprog** [comment]
I like it.. Anyone want to do a pull request on this?

**Comment by JoeLudwig** [comment]
Yeah, that's definitely the line I was thinking along. So the Handle field in Window is an HWND (on Windows)?

I need to finish actually finish hooking up the library to the rest of my stuff first, but I can take a look a a filter of this sort after that.

**Comment by smasherprog** [comment]
this code definitely belongs in the library, i agreeee

**Comment by JoeLudwig** [comment]
The snippet above helped tremendously. Do you think it makes sense to just apply that to the window list before return it to the application?

**Comment by smasherprog** [comment]
I think so.. capturing a window that is blank doesnt make much sense to me. 
So adding this to the GetWIndows() makes sens to me

**Comment by smasherprog** [comment]
Anyone willing to do a PR on this one?

**Comment by smasherprog** [comment]
Any traction on this? I think a Boolean indicating the window is hidden might be helpful. I want to make sure the list doesn't cause confusion about a window that actual exists, but isn't visible.

**Comment by Ozzadar** [comment]
I'll likely be looking at this; I've done this exact thing before just gotta find where it was. I think it was like... getting the list of handles in the taskbar or something.

**Comment by smasherprog** [comment]
Updated code to address this on windows. Only windows reachable via ALT TAB are reported back. 
I think this is the desired effect.
#110
Going to close this..
