### ISSUE TITLE
Many blank windows

### ISSUE THREAD

**Issue by JoeLudwig** [smasherprog/screen_capture_lite#87]
This could be related to #72 but doesn't seem to have anything to do with DX12, so I doubt it.

![image](https://user-images.githubusercontent.com/303656/86543109-72fed600-bed0-11ea-9368-8c8dd8a5852d.png)

This is every window that survives the filtering process described in #86. Some of them work fine, but most windows come out as all zeros (black and zero alpha.) In some cases (like the Steam client) some of content is captured, but most is not. One common thread seems to be that most of these windows (Hangouts, Chrome, a few windows from the Steam client) are all showing web content from Chromium.

The exception from that is the VR View window from SteamVR, which is a shared texture rendered by Qt.

Any idea what might be going on here? Can you repro the problem with the Steam client? It should be easy to get your hands on...

**Comment by smasherprog** [comment]
I have no idea whats going on here or exactly what you are trying to describe.
Are you saying you are doing VR and trying to stream windows into the VR world?

**Comment by JoeLudwig** [comment]
The VR part is just how I'm displaying the textures. The textures I'm getting out of the library are all black with zero alpha.

**Comment by JoeLudwig** [comment]
Sorry the previous screenshot was unclear. Here's an image of the Steam client window as captured by the screen_capture_lite example. The only changes I made was to change the "cmake" filter string to "steam" and uncomment the lines that save a JPG on each capture.

![2WINDIF_](https://user-images.githubusercontent.com/303656/86871128-88b9fa00-c08e-11ea-8088-f27ae1cc91b6.jpg)

**Comment by JoeLudwig** [comment]
Here's Chrome displaying this very bug:  It seems like all content rendered by Chromium is broken.

![5WINDIF_](https://user-images.githubusercontent.com/303656/86871378-05e56f00-c08f-11ea-9b82-1a6afabe05af.jpg)

**Comment by JoeLudwig** [comment]
I wonder if the missing content in these contexts is from owned windows. Chromium itself seems to explicitly walk them and copy them into the captured buffer when capturing desktop windows for RTC: https://chromium.googlesource.com/external/webrtc/+/refs/heads/lkgr/modules/desktop_capture/window_capturer_win.cc#422

**Comment by smasherprog** [comment]
hmmmmm interesting.... it will take me some time to get around to this.

**Comment by JoeLudwig** [comment]
Yeah I did some exploring in there and looked at the windows that aren't working in Spy++. It seems that in this case there aren't any popup windows, but there are layered windows and windows with the WS_EX_NOREDIRECTIONBITMAP style. I think those may need to be composited too.  I don't know if I'll get another chance to look before the weekend, but we'll see how it goes.

**Comment by JoeLudwig** [comment]
I trying to fix this bug I encounted another source of black windows: Moving a window to a secondary monitor.

That may be #81. I have 150% scaling on my primary monitor. The code to select the monitor DC seems about right, so I don't think it's that. (Though if a window moves from one monitor to another does that mean the capture object needs to be destroyed and recreate? How does an app know to do that?)

**Comment by smasherprog** [comment]
u Working in a fork? If you have a partial fix for this, lets get it into master!

**Comment by JoeLudwig** [comment]
I don't have anything working yet. I just local changes that are broken in new and interesting ways. :)

**Comment by smasherprog** [comment]
if you want to work in a branch ill help out

**Comment by JoeLudwig** [comment]
I can't make a branch in your repo, but here's a fork with my not-yet-functional changes: https://github.com/JoeLudwig/screen_capture_lite/tree/joe_working_on_blank_windows

I don't know if I'm using bitblt wrong, if I'm picking the wrong window, or what. Still a black rect for any of this type of content.

**Comment by JoeLudwig** [comment]
I'm beginning to think that the problem is that GDI can't read windows that only contain D3D output. So even when using BitBlt on the child windows directly it still returns black pixels. The "popup windows" thing in Chromium is mostly about menus and dialogs, I think.

**Comment by Electric-Turtle** [comment]
Perhaps it's worth looking into using the Windows GraphicsCapture API (the "modern" Windows way of doing this).

There is a (somewhat spaghetti-code) example [here](https://github.com/robmikh/Win32CaptureSample.git).
