### ISSUE TITLE
question. win10. monitor IDs are started from 1

### ISSUE THREAD

**Issue by RustamGamidov** [smasherprog/screen_capture_lite#88]
Hi, i'm experiencing an error with not being able to grab the screen on windows.
The only evidence i can catch now is *GetMonitors()* returns monitors with IDs starting from 1. In normal situation its 0 based.
I can't see from the code how this can happen.

Environment is a laptop, with external monitor attached. 
Laptop lid is closed and only the external monitor is in use.
It's not always the case, i'm trying to get steps to reproduce but not succeeded so far.
I saw it three time during two month.
The only workaround is a reboot.

Has anybody experienced similar behavior?

**Comment by smasherprog** [comment]
I havent seen this before.  You can see about how to fix it and issue a pull request on this.

**Comment by RustamGamidov** [comment]
My bad. That project i've been trying to fix is using old! version of the _screen_capture_lite_ and in that version there's bug.
Current version looks OK. Sorry for the noise
