### ISSUE TITLE
No new frames on macOS Catalina when running inside wxWidgets app

### ISSUE THREAD

**Issue by kolpav** [smasherprog/screen_capture_lite#91]
I have wxWidgets app displaying monitor output and it works on windows and linux but not on macos. I am sure it has to do something with Catalina's Privacy Protection where you need to allow access to things like screen capture for each app.

Strange thing is when I run screen_capture_lite as console application I get prompt asking for access and everything is working fine but when I run my wxWidgets app I never get prompted and only event I am getting is mouseChanged. Are there any prerequisites for running this library inside wxWidgets on macos catalina?

I know this is more of a question than issue with this library feel free to close.

**Comment by smasherprog** [comment]
I have used wxwidgets before. Maybe we need to add a call on app startup before wxwidgets?

**Comment by smasherprog** [comment]
Were you able to figure this one out?

**Comment by smasherprog** [comment]
Closing due to lack of information. Ill reopen if there's more info provided
