### ISSUE TITLE
Always capturing from 0,0 position

### ISSUE THREAD

**Issue by sarbjit-singh** [smasherprog/screen_capture_lite#92]
I am on following configuration:

OS: OSX

I am using the modified sample code to capture from offsetX > 0 and offsetY > 0 but it always is capturing from 0,0. It does respect the width and height though.

Am I doing anything wrong or is that a bug.

**Comment by smasherprog** [comment]
Im not sure, the code is pretty simple though to debug though. Let me know what you find. Pull Requests are always welcome!

**Comment by smasherprog** [comment]
Closing this due to lack of feedback
