### ISSUE TITLE
CMake Error: The following variables are used in this project, but they are set to NOTFOUND

### ISSUE THREAD

**Issue by rotolonico** [smasherprog/screen_capture_lite#93]
When loading the source code in CLion I get this error message:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_Xinerama_LIB (ADVANCED)
    linked by target "screen_capture_example" in directory {ProjectPath}/Example
X11_Xtst_LIB (ADVANCED)
    linked by target "screen_capture_example" in directory {ProjectPath}/Example

Am I doing something wrong? I am very new to C++ development.
Thanks!

**Comment by smasherprog** [comment]
you have to install these libraries on your system. depending on your linux version, 
apt-get install LIBRARYNAME
or 
yum install LIBRARYNAME

**Comment by rotolonico** [comment]
Thanks, I'll try that
