### ISSUE TITLE
tolower causes *** stack smashing detected ***: terminated

### ISSUE THREAD

**Issue by perara** [smasherprog/screen_capture_lite#94]
While in Linux environment, and having the following tab open in chrome:
https://unix.stackexchange.com/questions/14159/how-do-i-find-the-window-dimensions-and-position-accurately-including-decoration
I get the following error:
`*** stack smashing detected ***: terminated`

The line is found in GetWindows.cpp:L112
`std::transform(name.begin(), name.end(), std::begin(w.Name), ::tolower);`

Removing this line makes the program run as expected. Is the tolower really needed anyways?. I'm assuming the special characters in the window title is causing this issue?

**Comment by smasherprog** [comment]
If you can issue a PR ill merge it in. The tolower isnt needed

**Comment by perara** [comment]
See #95 95

**Comment by smasherprog** [comment]
Fixed by adding bounds check. I like the fact that all the windows names are tolowered. It makes finding names a bit easier if the library forces all window names to be tolower.

**Comment by midn1** [comment]
> It makes finding names a bit easier if the library forces all window names to be tolower.

I'm sorry but this makes no sense. If an interface claims to give you a window's name, *anyone* would expect to get the window name. Forcing it to be lowercase for your niche taste and/or use case is beyond ridiculous.

**Comment by midn1** [comment]
Not to mention that you're breaking Unicode compatibility.
