### ISSUE TITLE
Do we support Windows 7?

### ISSUE THREAD

**Issue by ababo** [smasherprog/screen_capture_lite#97]
I see that the recent changes involve usage of the following `winuser.h` constants:

```c
#if WINVER >= 0x0602
#define WS_EX_NOREDIRECTIONBITMAP __MSABI_LONG(0x00200000)
#endif

#if(_WIN32_WINNT >= 0x0603)
#define PW_RENDERFULLCONTENT    0x00000002
#endif /* _WIN32_WINNT >= 0x0603 */
```
which means we lose Win7 and Win8 support. Do we intentionally drop those versions?

**Comment by smasherprog** [comment]
I did remove support a while ago. This was only because debugging win7/win8/win10 was a pain in the ass. 
If you want to bring it back im open to that, but the old GDI capture code needs to be resurected and brought back into the codebase. done and working in the history of this project so its possible to bring it back quickly

**Comment by ababo** [comment]
IMO that doesn't look right to cut 19% of Win users.

**Comment by ababo** [comment]
Can you tell on which commit you drop the support?

**Comment by smasherprog** [comment]
it looks like I do support win7/8 all the code is in there and working
https://github.com/smasherprog/screen_capture_lite/blob/master/src/windows/GDIFrameProcessor.cpp
https://github.com/smasherprog/screen_capture_lite/blob/f83842f42bc8a4bf7fb32b9399d6422fdbf0d844/src/windows/ThreadRunner.cpp#L59
So, it might just be that someone needs to test and verify that it works on win7.

**Comment by smasherprog** [comment]
Its been a long time since i visited this code and I thought i removed support, but I was wrong, i just wont have a testing environment to make sure it works properly

**Comment by ababo** [comment]
Yes, have just verified. Nice to hear, thanks!

**Comment by smasherprog** [comment]
Closing this, reopen another issue if U find something else 👍
